### ISSUE TITLE
handle case where we dont need to declare a storage class

### ISSUE THREAD

**Issue by goern** [thoth-station/ansible-role-postgresql#14]
in some cases it might not be required to have a storage class declared for the pvc.

**Comment by saisankargochhayat** [comment]
Note - need to change - https://github.com/thoth-station/ansible-role-postgresql/blob/6cddb0aaee362531b24c111829d3ef22f30e9c13/tasks/postgresql.yml#L145
To `{{ MEMORY_LIMIT }}`
